# Generated by Django 4.1.6 on 2023-02-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='assigned_to',
            field=models.CharField(default='string', max_length=200),
        ),
        migrations.AddField(
            model_name='matter',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matter',
            name='category',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=200),
        ),
    ]
