# Generated by Django 4.1.6 on 2023-02-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
