# Generated by Django 4.1.6 on 2023-02-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
