# Generated by Django 4.1.6 on 2023-02-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_clientindividual_paralegal_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='assigned_to',
        ),
    ]
