# Generated by Django 4.1.6 on 2023-02-12 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_remove_matter_assigned_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paralegal',
            new_name='lawyer',
        ),
    ]
