# Generated by Django 4.1.6 on 2023-02-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_document_matter_remove_event_matter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Commercial', 'Commercial'), ('Litigation', 'Litigation'), ('Conveyancing', 'Conveyancing')], max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=200)),
                ('ref_code', models.CharField(blank=True, max_length=200)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('client', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_lawyer', to='base.lawyer')),
                ('original_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_lawyer', to='base.lawyer')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.matter'),
        ),
        migrations.AddField(
            model_name='event',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.matter'),
        ),
        migrations.AddField(
            model_name='note',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.matter'),
        ),
        migrations.AddField(
            model_name='task',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.matter'),
        ),
    ]
