# Generated by Django 4.1.6 on 2023-02-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_matter_document_matter_event_matter_note_matter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='matter',
        ),
        migrations.RemoveField(
            model_name='event',
            name='matter',
        ),
        migrations.RemoveField(
            model_name='matter',
            name='current_lawyer',
        ),
        migrations.RemoveField(
            model_name='matter',
            name='original_lawyer',
        ),
        migrations.RemoveField(
            model_name='note',
            name='matter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='matter',
        ),
        migrations.DeleteModel(
            name='ClientIndividual',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Matter',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
