# Generated by Django 4.1.6 on 2023-02-13 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_clientindividual_individualclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Business_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.businessclient'),
        ),
        migrations.AddField(
            model_name='task',
            name='Individual_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.individualclient'),
        ),
    ]
