# Generated by Django 4.1.6 on 2023-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_task_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=200),
        ),
    ]
