# Generated by Django 4.1.6 on 2023-02-27 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0028_remove_event_assigned_to_event_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
