# Generated by Django 4.1.6 on 2023-02-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Statutes', 'Statutes'), ('Letters', 'Letters'), ('Case Law', 'Case Law')], max_length=200),
        ),
    ]
