# Generated by Django 4.1.6 on 2023-03-02 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0034_alter_document_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('address', models.TextField()),
                ('currency_code', models.CharField(max_length=200)),
                ('tax_pin', models.CharField(max_length=200)),
                ('physical_address', models.TextField()),
                ('bank', models.CharField(max_length=200)),
                ('bank_account_name', models.CharField(max_length=200)),
                ('bank_account_number', models.CharField(max_length=200)),
                ('bank_branch', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feenote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('date_billed', models.DateField()),
                ('billable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('billed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('business_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.businessclient')),
                ('individual_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.individualclient')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.matter')),
            ],
        ),
    ]
